# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy JAR 파일
        run: cp build/libs/hello-world-0.0.1-SNAPSHOT.jar ${{ runner.workspace }}/app.jar
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "build/libs/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: "/app"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            nohup java -jar hello-world-0.0.1-SNAPSHOT.jar &
            

#      - name: Start SSH Agent
#        run: |
#          eval `ssh-agent -s`
#          ssh-add <(echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}")
#          ssh-keyscan -H ${{ secrets.SERVER_IP }} > ~/.ssh/known_hosts
#      - name: Deploy to Virtual Machine
#        run: |
#          ssh -o StrictHostKeyChecking=no -i ${{ runner.workspace }}/id_rsa root@101.101.211.188 "killall -9 java; nohup java -jar ~/app.jar &"
