name: CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
